// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLuyhuxUSe_rOOS_jqE4QlLroYzQlURc',
    appId: '1:828413775508:web:33b64eb9048ce287ac6e81',
    messagingSenderId: '828413775508',
    projectId: 'fanikishaapp',
    authDomain: 'fanikishaapp.firebaseapp.com',
    storageBucket: 'fanikishaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV61pweCzl9qJM4kZ27RNxiS5YtZatCN0',
    appId: '1:828413775508:android:2947ae582103a05bac6e81',
    messagingSenderId: '828413775508',
    projectId: 'fanikishaapp',
    storageBucket: 'fanikishaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vSx1mDUP0KCAR_lJQxNqx0TsBz0mdNY',
    appId: '1:828413775508:ios:b5f2d8db72f45fb5ac6e81',
    messagingSenderId: '828413775508',
    projectId: 'fanikishaapp',
    storageBucket: 'fanikishaapp.appspot.com',
    iosClientId: '828413775508-vt7afhq1u4b2dddh92k6emrstvslbrkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanikishaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6vSx1mDUP0KCAR_lJQxNqx0TsBz0mdNY',
    appId: '1:828413775508:ios:182c55922675b5d5ac6e81',
    messagingSenderId: '828413775508',
    projectId: 'fanikishaapp',
    storageBucket: 'fanikishaapp.appspot.com',
    iosClientId: '828413775508-hg4bc02igggvg2h891muerbghmsq18p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanikishaApp.RunnerTests',
  );
}
